# import numpy as np

arr = np.array((1, 2, 3, 4, 5))

print(arr)

In [2]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(type(arr))

<class 'numpy.ndarray'>


In [2]:
import numpy
a=numpy.array([1,2,3])
b=numpy.array(54)
c=numpy.array([[1,2,3],[4,5,6]])
d=numpy.array([[[1,2,3],[4,5,6]],[[7,8,9],[0,1,2]]])
print(a)
print(b)
print(c)
print(d)   

[1 2 3]
54
[[1 2 3]
 [4 5 6]]
[[[1 2 3]
  [4 5 6]]

 [[7 8 9]
  [0 1 2]]]


In [1]:
import numpy as np
arr=np.array([1,2,3,4])
print(arr[0])

1


# Asarray(), FROMBUFFER(),FROMITER()

In [2]:
import numpy as np

In [3]:
a=np.array([10,20.30,40])

In [4]:
print(a)

[10.  20.3 40. ]


In [7]:
res=np.asarray(a,dtype="int",order="c")
#here c means row

In [8]:
print(res)

[10 20 40]


In [9]:
b=np.array([[10,20,30],[40,50,60]])

In [10]:
print(b)

[[10 20 30]
 [40 50 60]]


In [13]:
res1=np.asarray(b,dtype="float",order="F")
# F is used to column measure order but by default it will print row order

In [14]:
print(res1)

[[10. 20. 30.]
 [40. 50. 60.]]


In [15]:
for i in np.nditer(res1):
    print(i)

10.0
40.0
20.0
50.0
30.0
60.0


In [17]:
res2=np.asarray(b,dtype="float",order="c")

In [18]:
for i in np.nditer(res2):
    print(i)

10.0
20.0
30.0
40.0
50.0
60.0


In [19]:
print(res2)

[[10. 20. 30.]
 [40. 50. 60.]]


In [20]:
s=b"hello welcome to the python"

In [24]:
c=np.frombuffer(s,dtype="S1",count=-1,offset=0)

In [26]:
print(c)

[b'h' b'e' b'l' b'l' b'o' b' ' b'w' b'e' b'l' b'c' b'o' b'm' b'e' b' '
 b't' b'o' b' ' b't' b'h' b'e' b' ' b'p' b'y' b't' b'h' b'o' b'n']


In [27]:
c=np.frombuffer(s,dtype="S1",count=10,offset=0)

In [28]:
print(c)

[b'h' b'e' b'l' b'l' b'o' b' ' b'w' b'e' b'l' b'c']


In [29]:
c=np.frombuffer(s,dtype="S1",count=10,offset=6)
print(c)

[b'w' b'e' b'l' b'c' b'o' b'm' b'e' b' ' b't' b'o']


In [30]:
list=[10,20,30,40,50]

In [31]:
d=np.fromiter(list,dtype="float",count=-1)
print(d)
#count -1 means whole value will be printed

[10. 20. 30. 40. 50.]


In [32]:
d=np.fromiter(list,dtype="S1",count=-1)
print(d)
#S1 means one byte data

[b'1' b'2' b'3' b'4' b'5']


In [33]:
d=np.fromiter(list,dtype="S1",count=2)
print(d)

[b'1' b'2']


# ARANGE() LINESPACE() lOGSPACE()

In [1]:
import numpy as np

In [2]:
np.arange(0,10,2,dtype="int")

array([0, 2, 4, 6, 8])

In [3]:
arr=np.arange(0,10,2,dtype="int")

In [4]:
print(arr)

[0 2 4 6 8]


In [8]:
arr=np.arange(0,10,2,dtype="float")
print(arr)
#10 will not be included

[0. 2. 4. 6. 8.]


In [9]:
arr1=np.linspace(0,10,5,)
print(arr1)
#by using linespace function 10 will be included

[ 0.   2.5  5.   7.5 10. ]


In [10]:
arr1=np.linspace(0,10,5,endpoint=False)
print(arr1)

[0. 2. 4. 6. 8.]


In [11]:
arr1=np.linspace(0,10,5,endpoint=True)
print(arr1)

[ 0.   2.5  5.   7.5 10. ]


In [12]:
arr1=np.linspace(0,10,5,endpoint=False,retstep=True)
print(arr1)

(array([0., 2., 4., 6., 8.]), 2.0)


In [14]:
arr1=np.linspace(0,10,endpoint=False,)
print(arr1)
#by default it would print 50

[0.  0.2 0.4 0.6 0.8 1.  1.2 1.4 1.6 1.8 2.  2.2 2.4 2.6 2.8 3.  3.2 3.4
 3.6 3.8 4.  4.2 4.4 4.6 4.8 5.  5.2 5.4 5.6 5.8 6.  6.2 6.4 6.6 6.8 7.
 7.2 7.4 7.6 7.8 8.  8.2 8.4 8.6 8.8 9.  9.2 9.4 9.6 9.8]


In [16]:
arr1=np.linspace(0,10,5,endpoint=False,dtype="int")
print(arr1)

[0 2 4 6 8]


In [17]:
arr1=np.linspace(0,10,2,endpoint=False,retstep=True)
print(arr1)

(array([0., 5.]), 5.0)


In [23]:
np.linspace(0,10,)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [24]:
arr2=np.logspace(0,10,num=4,endpoint=False)
print(arr2)

[1.00000000e+00 3.16227766e+02 1.00000000e+05 3.16227766e+07]


In [25]:
arr2=np.logspace(0,10,num=4,endpoint=False,base=2)
print(arr2)

[  1.           5.65685425  32.         181.01933598]


In [26]:
arr2=np.logspace(0,10,endpoint=False,base=2)
print(arr2)

[  1.           1.14869835   1.31950791   1.51571657   1.74110113
   2.           2.29739671   2.63901582   3.03143313   3.48220225
   4.           4.59479342   5.27803164   6.06286627   6.96440451
   8.           9.18958684  10.55606329  12.12573253  13.92880901
  16.          18.37917368  21.11212657  24.25146506  27.85761803
  32.          36.75834736  42.22425314  48.50293013  55.71523605
  64.          73.51669472  84.44850629  97.00586026 111.4304721
 128.         147.03338944 168.89701258 194.01172051 222.8609442
 256.         294.06677888 337.79402516 388.02344103 445.72188841
 512.         588.13355776 675.58805032 776.04688205 891.44377682]


# intializing arrays zeros(),Ones(),Full(),Eye()

In [27]:
import numpy as np

In [29]:
a=np.array([10,20,30,40,50,60])
print(a)

[10 20 30 40 50 60]


In [31]:
np.shape(a)

(6,)

In [32]:
a=np.array([[10,20,30],[40,50,60]])
print(a)
#two dimension each dimension have three elements

[[10 20 30]
 [40 50 60]]


In [33]:
np.shape(a)

(2, 3)

In [34]:
a=np.array([[10,20],[30,40],[50,60]])
print(a)
#three dimension each dimension have two elements

[[10 20]
 [30 40]
 [50 60]]


In [35]:
np.shape(a)

(3, 2)

In [36]:
a=np.array([10,20,30,40,50,60])
print(a)

[10 20 30 40 50 60]


In [37]:
np.shape(a)

(6,)

In [39]:
np.reshape(a,(3,2))

array([[10, 20],
       [30, 40],
       [50, 60]])

In [40]:
print(a)

[10 20 30 40 50 60]


In [41]:
np.reshape(a,(2,3))

array([[10, 20, 30],
       [40, 50, 60]])

In [44]:
print(a)

[10 20 30 40 50 60]


In [47]:
a=np.array([[10,20],[30,40],[50,60]])
print(a)

[[10 20]
 [30 40]
 [50 60]]


In [49]:
np.reshape(a,(2,3))

array([[10, 20, 30],
       [40, 50, 60]])

In [55]:
np.zeros((4,4),dtype="int")

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [57]:
np.ones((4,4),dtype="int")

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [60]:
np.full((2,3),"Deepak")

array([['Deepak', 'Deepak', 'Deepak'],
       ['Deepak', 'Deepak', 'Deepak']], dtype='<U6')

In [64]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [65]:
a=np.array([10,20,30,40,50,60])
print(a)

[10 20 30 40 50 60]


In [66]:
print(a[0])

10


In [68]:
print(a[4])

50


In [69]:
print(a[-2])

50


In [78]:
b=np.array([[10,20,30,40,],[50,60,70,80]])
print(b)
print(b[0,3])
print(b[0,-2])
print(b[-1,-2])

[[10 20 30 40]
 [50 60 70 80]]
40
30
70


In [90]:
c=np.array([[[10,20,30],[40,50,60]],[[70,80,90],[100,110,120]]])
print(c)
print(c[0,1,2])
print(c[1,0,1])
print(c[1,1,2])
print(c[0,0,2])
print(c[0,0,0])
print(c[1,1,1])
print(c[-2,-1,-2])
print(c[-2,-2,-3])
#3d array

[[[ 10  20  30]
  [ 40  50  60]]

 [[ 70  80  90]
  [100 110 120]]]
60
80
120
30
10
110
50
10


# Slicing operation in nd array

In [91]:
import numpy as np

In [112]:
a=np.array([10,20,30,40,50,60])
print(a)
print(a[:])
print(a[::3])
print(a[:3])
print(a[::-3])
print(a[-1:])
print(a[-1::-1])

[10 20 30 40 50 60]
[10 20 30 40 50 60]
[10 40]
[10 20 30]
[60 30]
[60]
[60 50 40 30 20 10]


In [119]:
b=np.array([[10,20,30,40],[50,60,70,80]])
print(b)
print(b[0,0:3])
print(b[1,2:])
print(b[0:2,0:2])


[[10 20 30 40]
 [50 60 70 80]]
[10 20 30]
[70 80]
[[10 20]
 [50 60]]


In [129]:
c=np.array([[[10,20,30,],[40,50,60]],[[80,90,100],[90,100,110]]])
print(c)
print(c[1,0,0:2])
print(c[1,1,0:2])
print(c[1,1,-1::-1])
print(c[0:2,0:2,0:2])

[[[ 10  20  30]
  [ 40  50  60]]

 [[ 80  90 100]
  [ 90 100 110]]]
[80 90]
[ 90 100]
[110 100  90]
[[[ 10  20]
  [ 40  50]]

 [[ 80  90]
  [ 90 100]]]


In [130]:
import numpy as np

In [148]:
a=np.array([10,0,30,40,50])
print(a)
print(a.dtype)
b=a.astype("bool")
print(b)
print(b.dtype)

[10  0 30 40 50]
int32
[ True False  True  True  True]
bool


In [155]:
a=np.array([10,0,30,40,50])
print(a)
c=a.copy()
print(c)
c[1]=100
print(a,c)
v=a.view()
print(v)
v[1]=100
print(a,v)
print(a.base)
print(c.base)

[10  0 30 40 50]
[10  0 30 40 50]
[10  0 30 40 50] [ 10 100  30  40  50]
[10  0 30 40 50]
[ 10 100  30  40  50] [ 10 100  30  40  50]
None
None


# axis attribute

In [156]:
import numpy as np

In [167]:
a=np.array([[10,20,30,40],[50,60,70,80]])
print(a)
np.sort(a,axis=0)
print(a)
np.sort(a,axis=1)
print(a)
#0 means row operation
#1 means columun operation

[[10 20 30 40]
 [50 60 70 80]]
[[10 20 30 40]
 [50 60 70 80]]
[[10 20 30 40]
 [50 60 70 80]]


# JOINING ARRAYS (CONCATENATE()....

In [168]:
import numpy as np

In [169]:
a=np.arange(6).reshape(2,3)

In [170]:
a

array([[0, 1, 2],
       [3, 4, 5]])

In [171]:
b=np.arange(7,13).reshape(2,3)

In [172]:
b

array([[ 7,  8,  9],
       [10, 11, 12]])

In [173]:
np.concatenate((a,b))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 7,  8,  9],
       [10, 11, 12]])

In [175]:
np.concatenate((a,b),axis=1)

array([[ 0,  1,  2,  7,  8,  9],
       [ 3,  4,  5, 10, 11, 12]])

In [184]:
np.stack((a,b),axis=1)

array([[[ 0,  1,  2],
        [ 7,  8,  9]],

       [[ 3,  4,  5],
        [10, 11, 12]]])

In [185]:
np.vstack((a,b))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 7,  8,  9],
       [10, 11, 12]])

In [186]:
np.hstack((a,b))

array([[ 0,  1,  2,  7,  8,  9],
       [ 3,  4,  5, 10, 11, 12]])

In [187]:
np.dstack((a,b))

array([[[ 0,  7],
        [ 1,  8],
        [ 2,  9]],

       [[ 3, 10],
        [ 4, 11],
        [ 5, 12]]])

# SPLITTING ARRAY

In [190]:
import numpy as np

In [191]:
a=np.arange(10)

In [192]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [193]:
np.split(a,2)

[array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9])]

In [194]:
np.array_split(a,3)

[array([0, 1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]

In [195]:
np.hsplit(a,2)

[array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9])]

In [198]:
c=np.arange(6).reshape(2,3)
print(c)

[[0 1 2]
 [3 4 5]]


In [200]:
np.vsplit(c,2)

[array([[0, 1, 2]]), array([[3, 4, 5]])]

# SEARCH IN NUMY(WHERE()

In [202]:
import numpy as np

In [205]:
a=np.arange(10,100,10)

In [206]:
a

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [207]:
np.where(a==40)

(array([3], dtype=int64),)

In [208]:
a=np.array([10,10,20,30,40,50,10,10])

In [209]:
np.where(a==10)

(array([0, 1, 6, 7], dtype=int64),)

In [210]:
np.where(a%20==0)

(array([2, 4], dtype=int64),)

In [212]:
a=np.array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [215]:
np.searchsorted(a,[15,25,35])

array([1, 2, 3], dtype=int64)

# SORT() IN NUMPY

In [216]:
import numpy as np

In [218]:
a=np.array([50,40,10,20,30])

In [219]:
print(a)

[50 40 10 20 30]


In [220]:
np.sort(a)

array([10, 20, 30, 40, 50])

In [221]:
b=np.array([[50,40,30],[20,10,90]])
print(b)

[[50 40 30]
 [20 10 90]]


In [224]:
np.sort(b,axis=1)

array([[30, 40, 50],
       [10, 20, 90]])

In [225]:
import numpy as np

In [229]:
d=np.dtype([("s10"),float])

TypeError: Field elements must be 2- or 3-tuples, got ''s10''

# AIRTHMATIC OPERATIONS ON ARRAY

In [5]:
import numpy as np

In [6]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [7]:
b=np.array([[1,1,1],[1,1,1],[1,1,1]])

In [9]:
print(a,b)

[[1 2 3]
 [4 5 6]
 [7 8 9]] [[1 1 1]
 [1 1 1]
 [1 1 1]]


In [10]:
np.shape(a)

(3, 3)

In [11]:
np.shape(b)

(3, 3)

In [12]:
np.add(a,b)

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [15]:
c=np.array([10,20,30])
print(c)

[10 20 30]


In [16]:
np.add(a,c)

array([[11, 22, 33],
       [14, 25, 36],
       [17, 28, 39]])

In [17]:
d=np.array([10,20])
np.shape(d)

(2,)

In [18]:
np.add(a,d)

ValueError: operands could not be broadcast together with shapes (3,3) (2,) 

In [22]:
e=np.array([10])
print(e)
np.shape(e)

[10]


(1,)

In [23]:
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [24]:
np.add(a,e)

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [25]:
np.subtract(a,e)

array([[-9, -8, -7],
       [-6, -5, -4],
       [-3, -2, -1]])

In [26]:
print(b)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [29]:
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [27]:
np.subtract(a,b)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [28]:
np.multiply(a,b)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [30]:
np.divide(a,b)

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [32]:
#other mathematical operation can do by same

In [35]:
np.mod(a,b)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [36]:
np.power(a,3)

array([[  1,   8,  27],
       [ 64, 125, 216],
       [343, 512, 729]], dtype=int32)

In [37]:
np.mod(a,10)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]], dtype=int32)

In [38]:
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [39]:
np.reciprocal(a)

array([[1, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [42]:
complex=np.array([5+6j,10-5j,9+7j])
print(complex)

[ 5.+6.j 10.-5.j  9.+7.j]


In [43]:
np.real(complex)

array([ 5., 10.,  9.])

In [44]:
np.imag(complex)

array([ 6., -5.,  7.])

In [46]:
np.conjugate(complex)

array([ 5.-6.j, 10.+5.j,  9.-7.j])

# Stastical function mean median mode

In [47]:
import numpy as np

In [48]:
a=np.array([[10,20,30],[50,70,60],[1,2,3]])

In [49]:
print(a)

[[10 20 30]
 [50 70 60]
 [ 1  2  3]]


In [50]:
np.amin(a)

1

In [51]:
np.amax(a)

70

In [52]:
np.amin(a,axis=0)

array([1, 2, 3])

In [53]:
np.amax(a,axis=1)

array([30, 70,  3])

In [54]:
np.amax(a,axis=0)

array([50, 70, 60])

In [55]:
np.amax(a,axis=1)

array([30, 70,  3])

In [56]:
print(a)

[[10 20 30]
 [50 70 60]
 [ 1  2  3]]


In [57]:
np.average(a)

27.333333333333332

In [58]:
w=[1,2,3]

In [62]:
np.average(a,weights=w,axis=0)

array([18.83333333, 27.66666667, 26.5       ])

In [64]:
np.average(a,weights=w,axis=1)
#axis=1 means row wise operation

array([23.33333333, 61.66666667,  2.33333333])

In [65]:
print(a)

[[10 20 30]
 [50 70 60]
 [ 1  2  3]]


In [66]:
np.mean(a)

27.333333333333332

In [67]:
np.mean(a,axis=0)

array([20.33333333, 30.66666667, 31.        ])

In [68]:
np.mean(a,axis=1)

array([20., 60.,  2.])

In [69]:
print(a)

[[10 20 30]
 [50 70 60]
 [ 1  2  3]]


In [70]:
np.median(a)

20.0

In [71]:
np.median(a,axis=0)

array([10., 20., 30.])

In [72]:
np.median(a,axis=1)

array([20., 60.,  2.])

In [75]:
print(a)

[[10 20 30]
 [50 70 60]
 [ 1  2  3]]


In [73]:
np.var(a)

632.2222222222223

In [74]:
np.std(a)

25.144029554194816